data_path: "/home/daniel/ssd/data/celebA"
# DSPRITES = 1
# CELEBA = 2
# CHAIRS = 3
dataset: 2
in_memory: True
# FC_ENCODER = 1
# CONV_ENCODER = 2
# CONV_BN_ENCODER = 3
encoder: 2
# FC_DECODER = 1
# DECONV_DECODER = 2
# DECONV_BN_DECODER = 3
decoder: 2
# L2_LOSS = 1
# BERNOULLI = 2
rec_loss: 1
gamma_objective: True
gamma: 1000
C: 50
C_steps: 100000
z_dim: 32
lr: 0.0001
reduction: "mean"
